# Current Admin API Routes

# User Management
users:
  - method: GET
    path: /api/v1/users
    description: List all users
    authorization: [admin]
    implementation: Complete
    controller: UserController
    endpoint: getAllUsers

# Product Management
products:
  - method: POST
    path: /api/v1/products
    description: Create a new product
    authorization: [admin]
    implementation: Complete
    controller: ProductController
    endpoint: createProduct

  - method: PUT
    path: /api/v1/products/:id
    description: Update an existing product
    authorization: [admin]
    implementation: Complete
    controller: ProductController
    endpoint: updateProduct

  - method: DELETE
    path: /api/v1/products/:id
    description: Delete a product
    authorization: [admin]
    implementation: Complete
    controller: ProductController
    endpoint: deleteProduct

# Order Management
orders:
  - method: GET
    path: /api/v1/admin/orders
    description: List all orders (admin view)
    authorization: [admin]
    implementation: Complete
    controller: OrderController
    endpoint: getAllOrders

  - method: PUT
    path: /api/v1/orders/:id/status
    description: Update order status
    authorization: [admin]
    implementation: Complete
    controller: OrderController
    endpoint: updateOrderStatus

# Payment Management
payments:
  - method: PUT
    path: /api/v1/payments/:id/refund
    description: Process a refund for a payment
    authorization: [admin]
    implementation: Complete
    controller: PaymentController
    endpoint: refundPayment

  - method: PUT
    path: /api/v1/payments/:id/status
    description: Update payment status
    authorization: [admin]
    implementation: Complete
    controller: PaymentController
    endpoint: updatePaymentStatus

# Invoice Management
invoices:
  - method: PUT
    path: /api/v1/invoices/:id/status
    description: Update invoice status
    authorization: [admin]
    implementation: Complete
    controller: InvoiceController
    endpoint: updateInvoiceStatus

# Shipping Management
shipping:
  - method: POST
    path: /api/v1/shipping/methods
    description: Create a shipping method
    authorization: [admin]
    implementation: Complete
    controller: ShippingController
    endpoint: createShippingMethod

  - method: PUT
    path: /api/v1/shipping/methods/:id
    description: Update a shipping method
    authorization: [admin]
    implementation: Complete
    controller: ShippingController
    endpoint: updateShippingMethod

  - method: PUT
    path: /api/v1/orders/:orderId/shipping
    description: Update order shipping status
    authorization: [admin]
    implementation: Complete
    controller: ShippingController
    endpoint: updateOrderShippingStatus

  - method: POST
    path: /api/v1/orders/:orderId/shipping/label
    description: Generate shipping label
    authorization: [admin]
    implementation: Complete
    controller: ShippingController
    endpoint: generateShippingLabel

# Image Management
images:
  - method: GET
    path: /api/v1/images
    description: List all images
    authorization: [admin]
    implementation: Complete
    controller: ImageController
    endpoint: listImages

# Blog Management
blog:
  - method: POST
    path: /api/v1/blog/categories
    description: Create a blog category
    authorization: [admin]
    implementation: Complete
    controller: BlogController
    endpoint: createCategory

  - method: PUT
    path: /api/v1/blog/categories/:id
    description: Update a blog category
    authorization: [admin]
    implementation: Complete
    controller: BlogController
    endpoint: updateCategory

  - method: DELETE
    path: /api/v1/blog/categories/:id
    description: Delete a blog category
    authorization: [admin]
    implementation: Complete
    controller: BlogController
    endpoint: deleteCategory

  - method: POST
    path: /api/v1/blog/posts
    description: Create a blog post
    authorization: [admin]
    implementation: Complete
    controller: BlogController
    endpoint: createPost

  - method: PUT
    path: /api/v1/blog/posts/:id
    description: Update a blog post
    authorization: [admin]
    implementation: Complete
    controller: BlogController
    endpoint: updatePost

  - method: DELETE
    path: /api/v1/blog/posts/:id
    description: Delete a blog post
    authorization: [admin]
    implementation: Complete
    controller: BlogController
    endpoint: deletePost

  - method: PUT
    path: /api/v1/blog/posts/:id/status
    description: Update blog post status
    authorization: [admin]
    implementation: Complete
    controller: BlogController
    endpoint: updatePostStatus

# Implemented Admin APIs (Previously Missing)
implemented:
  product_attributes:
    - method: GET
      path: /api/v1/admin/product-attributes
      description: List all product attributes
      authorization: [admin]
      implementation: Complete
      controller: ProductAttributeController
      endpoint: getAllAttributes

    - method: GET
      path: /api/v1/admin/product-attributes/:id
      description: Get a product attribute by ID
      authorization: [admin]
      implementation: Complete
      controller: ProductAttributeController
      endpoint: getAttribute

    - method: POST
      path: /api/v1/admin/product-attributes
      description: Create a product attribute
      authorization: [admin]
      implementation: Complete
      controller: ProductAttributeController
      endpoint: createAttribute

    - method: PUT
      path: /api/v1/admin/product-attributes/:id
      description: Update a product attribute
      authorization: [admin]
      implementation: Complete
      controller: ProductAttributeController
      endpoint: updateAttribute

    - method: DELETE
      path: /api/v1/admin/product-attributes/:id
      description: Delete a product attribute
      authorization: [admin]
      implementation: Complete
      controller: ProductAttributeController
      endpoint: deleteAttribute

  product_variants:
    - method: GET
      path: /api/v1/admin/products/:productId/variants
      description: List all variants for a product
      authorization: [admin]
      implementation: Complete
      controller: ProductVariantController
      endpoint: getProductVariants

    - method: POST
      path: /api/v1/admin/products/:productId/variants
      description: Create a product variant
      authorization: [admin]
      implementation: Complete
      controller: ProductVariantController
      endpoint: createProductVariant

    - method: PUT
      path: /api/v1/admin/products/:productId/variants/:id
      description: Update a product variant
      authorization: [admin]
      implementation: Complete
      controller: ProductVariantController
      endpoint: updateProductVariant

    - method: DELETE
      path: /api/v1/admin/products/:productId/variants/:id
      description: Delete a product variant
      authorization: [admin]
      implementation: Complete
      controller: ProductVariantController
      endpoint: deleteProductVariant

  inventory:
    - method: GET
      path: /api/v1/admin/inventory
      description: List all inventory items
      authorization: [admin]
      implementation: Complete
      controller: InventoryController
      endpoint: getAllInventory

    - method: PUT
      path: /api/v1/admin/inventory/:variantId
      description: Update inventory for a product variant
      authorization: [admin]
      implementation: Complete
      controller: InventoryController
      endpoint: updateInventory

    - method: POST
      path: /api/v1/admin/inventory/bulk
      description: Bulk update inventory
      authorization: [admin]
      implementation: Complete
      controller: InventoryController
      endpoint: bulkUpdateInventory

  product_categories:
    - method: POST
      path: /api/v1/admin/product-categories
      description: Create a product category
      authorization: [admin]
      implementation: Complete
      controller: ProductCategoryController
      endpoint: createProductCategory

    - method: PUT
      path: /api/v1/admin/product-categories/:id
      description: Update a product category
      authorization: [admin]
      implementation: Complete
      controller: ProductCategoryController
      endpoint: updateProductCategory

    - method: DELETE
      path: /api/v1/admin/product-categories/:id
      description: Delete a product category
      authorization: [admin]
      implementation: Complete
      controller: ProductCategoryController
      endpoint: deleteProductCategory

# Implementation Summary
implementation_summary:
  phase_1:
    description: "Product Attributes and Variants Management"
    status: "Completed"
    tasks:
      - Created ProductAttributeController ✓
      - Added API endpoints for product attributes ✓
      - Added API endpoints for product variants ✓

  phase_2:
    description: "Inventory Management"
    status: "Completed"
    tasks:
      - Created InventoryController ✓
      - Implemented inventory update endpoints ✓
      - Implemented bulk inventory operations ✓

  phase_3:
    description: "Product Categories Management"
    status: "Completed"
    tasks:
      - Added API endpoints for product categories ✓

  next_steps:
    description: "Potential Enhancements"
    tasks:
      - Add comprehensive input validation for admin APIs
      - Implement pagination for list endpoints
      - Add filtering and sorting options to list endpoints
      - Add API documentation with Swagger/OpenAPI
