name = "ecommerce-api"
main = "dist/index.js"
compatibility_date = "2023-09-16"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
watch_dir = "src"

# ---------------------------
# Development environment
[env.dev]
name = "ecommerce-api-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "blissmaa-dev-db"
database_id = "4d3692c0-1dce-4310-bfda-bda7917a89ab"

[[env.dev.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "blissmaa-dev-images"

[env.dev.vars]
ENVIRONMENT = "development"
FIREBASE_PROJECT_ID = "your-firebase-project-id"
DELHIVERY_API_KEY = "your-delhivery-api-key"
RAZORPAY_KEY_ID = "your-razorpay-key-id"
RAZORPAY_KEY_SECRET = "your-razorpay-key-secret"
RAZORPAY_WEBHOOK_SECRET = "your-razorpay-webhook-secret"
CLOUDFLARE_ACCOUNT_ID = "your-cloudflare-account-id"
CLOUDFLARE_API_TOKEN = "your-cloudflare-api-token"
CLOUDFLARE_IMAGES_HASH = "your-cloudflare-images-hash"

# ---------------------------
# Staging environment
[env.staging]
name = "ecommerce-api-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "blissmaa-prod-db"
database_id = "499e52b9-dd7d-4c37-ad40-9f54638c98c1"

[[env.staging.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "blissmaa-prod-images"

[env.staging.vars]
ENVIRONMENT = "staging"
FIREBASE_PROJECT_ID = ""
DELHIVERY_API_KEY = ""
RAZORPAY_KEY_ID = ""
RAZORPAY_KEY_SECRET = ""
RAZORPAY_WEBHOOK_SECRET = ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""
CLOUDFLARE_IMAGES_HASH = ""

# ---------------------------
# Production environment
[env.production]
name = "ecommerce-api"

[[env.production.d1_databases]]
binding = "DB"
database_name = "blissmaa-prod-db"
database_id = "499e52b9-dd7d-4c37-ad40-9f54638c98c1"

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "blissmaa-prod-images"

[env.production.vars]
ENVIRONMENT = "production"
FIREBASE_PROJECT_ID = ""
DELHIVERY_API_KEY = ""
RAZORPAY_KEY_ID = ""
RAZORPAY_KEY_SECRET = ""
RAZORPAY_WEBHOOK_SECRET = ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""
CLOUDFLARE_IMAGES_HASH = ""